import type { Metadata } from "next";
import Header from "@/components/Header";
import "./globals.css";
import { geistMono, geistSans, roboto } from "@/utils/fonts";
import Script from "next/script";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-black antialiased`}
      >
        <Header />
        {children}


    


       
      </body>
    </html>
  );
}
