import { headers } from "next/headers";
import type { Metadata } from "next";
import Header from "@/components/Header";
import "./globals.css";
import { geistMono, geistSans } from "@/utils/fonts";
import Script from "next/script";


export const dynamic = "force-dynamic"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const nonce = (await headers()).get('x-nouce')
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-black antialiased`}
      >
        <Header />
        {children}


    
      <Script
          strategy="afterInteractive"
          id="nonce-script"
          nonce={nonce as string}
          dangerouslySetInnerHTML={{
            __html: `__webpack_nonce__ = ${JSON.stringify(nonce)}`,
          }}
        />

       
      </body>
    </html>
  );
}
